version: '3.8'

services:
  gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - order_service
      - product_service
    networks:
      - app_network

  user_service:
    build: ./services/user_service
    ports:
      - "8001:8001"
    networks:
      - app_network

  order_service:
    build: ./services/order_service
    ports:
      - "8002:8002"
    networks:
      - app_network

  product_service:
    build: ./services/product_service
    ports:
      - "8003:8003"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
