version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"   # Cổng cho message broker
      - "15672:15672" # Cổng quản lý web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - order_service
      - product_service
      - rabbitmq
    networks:
      - app_network

  user_service:
    build: ./services/user_service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    networks:
      - app_network

  order_service:
    build: ./services/order_service
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
    networks:
      - app_network

  product_service:
    build: ./services/product_service
    ports:
      - "8003:8003"
    depends_on:
      - rabbitmq
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
