# Generated by Django 4.2 on 2025-04-05 08:08

from django.db import migrations, models
import django.db.models.deletion
import product_service.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangSanXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHangSanXuat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenKhuyenMai', models.CharField(max_length=100)),
                ('GiamGia', models.DecimalField(decimal_places=0, max_digits=2)),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ThongSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenThongSo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product_service.apps.products.models.product_image_path),
        ),
        migrations.AddField(
            model_name='product',
            name='hang_san_xuat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.hangsanxuat'),
        ),
        migrations.AddField(
            model_name='product',
            name='khuyen_mai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.khuyenmai'),
        ),
        migrations.AddField(
            model_name='product',
            name='thong_so',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.thongso'),
        ),
    ]
