CREATE DATABASE order_service_db;
USE order_service_db;

-- Tạo bảng TrangThai
CREATE TABLE TrangThai (
    MaTrangThai INT AUTO_INCREMENT PRIMARY KEY,
    TenTrangThai VARCHAR(50) NOT NULL,
    LoaiTrangThai VARCHAR(30) NOT NULL
);

-- Tạo bảng DonHang
CREATE TABLE DonHang (
    MaDonHang INT AUTO_INCREMENT PRIMARY KEY,
    MaNguoiDung INT NOT NULL,
    NgayDatHang TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaTrangThai INT NOT NULL,
    TongTien DECIMAL(9,0) NOT NULL,
    -- FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaTrangThai) REFERENCES TrangThai(MaTrangThai) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Tạo bảng ChiTietDonHang
CREATE TABLE ChiTietDonHang (
    MaChiTietDonHang INT AUTO_INCREMENT PRIMARY KEY,
    MaDonHang INT NOT NULL,
    MaSanPham INT NOT NULL,
    SoLuong INT NOT NULL,
    FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang) ON DELETE CASCADE ON UPDATE CASCADE
    -- FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham) ON DELETE CASCADE ON UPDATE CASCADE
);
